import type { Metadata } from "next";
import "./globals.css";
import "../styles/fonts.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="PKi6uptErITQMi-7ukLOFBZk_keBDUIl2XqPSOvZBTk"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
